apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: w25j1vh2u-dotnet-basic
  janus-idp.io/tekton: w25j1vh2u-dotnet-basic
  backstage.io/kubernetes-id: w25j1vh2u-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: w25j1vh2u-dotnet-basic
resources:
- deployment.yaml
- route.yaml
- service.yaml
